name: Install dependencies
description: Setup for node. pnpm and dependencies
inputs:
  node-version:
    required: false
    description: Node version for setup-node
    default: 20.x
  dotnet-version:
    required: false
    description: Node version for setup-node
    default: 9.0.x

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v3

    - name: Set node version to ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Set dotnet version to ${{ inputs.node-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
