packages:
  - "packages/*"
  - "samples/*"

catalog:
  "@alloy-js/cli": ~0.16.0
  "@alloy-js/core": ~0.16.0
  "@alloy-js/typescript": ~0.16.0
  "@alloy-js/rollup-plugin": ^0.1.0
  "@modelcontextprotocol/inspector": ^0.12.0
  "@modelcontextprotocol/sdk": ^1.11.4
  "@rollup/plugin-babel": ^6.0.4
  "@types/node": ^22.15.0
  "@typespec/compiler": ^1.0.0
  "@typespec/emitter-framework": 0.7.1
  "@typespec/http": ^1.0.1
  "@typespec/http-client": 0.7.0-dev.1
  "http-client-js-for-mcp": 0.0.0-2
  "@typespec/openapi": ^1.0.0
  "@typespec/openapi3": ^1.0.0
  "@typespec/rest": ^0.70.0
  "@typespec/tspd": "^0.70.0"
  concurrently: ^9.1.2
  prettier: ^3.5.3
  typescript: ^5.8.3
  typespec-zod: 0.0.0-51
  vitest: ^3.1.1
